Repository ezsystems/ezplatform-core, pull requests merged in 2019-04, with the labels that each got.

#4 EZP-30364: Wrong paths are generated for Encore configs when bundle is symlinked
  src/EzPlatformEncoreBundle/bundle/DependencyInjection/EzSystemsEzPlatformEncoreExtension.php
Labels: bug

#6 ADD custom webpack.config.js in bundles
  src/EzPlatformEncoreBundle/bundle/DependencyInjection/EzSystemsEzPlatformEncoreExtension.php
Labels: QA approved

#7 EZP-30479: Compile assets script is not working on some setups
  src/EzPlatformEncoreBundle/bundle/Command/CompileAssetsCommand.php
  src/EzPlatformEncoreBundle/bundle/Composer/ScriptHandler.php
Labels: Bug, QA approved
