Repository ezsystems/ezplatform-core, pull requests merged in 2020-10, with the labels that each got.

#19 EZP-31986: CompileAssetsCommand does not throw an exception when failing
  src/EzPlatformEncoreBundle/bundle/Command/CompileAssetsCommand.php
Labels: Improvement, Ready for QA

#20 EZP-31986: Added missing RuntimeException import to CompileAssetsCommand
  src/EzPlatformEncoreBundle/bundle/Command/CompileAssetsCommand.php
Labels: Bug

#21 EZP-32096: Provided possibility to configure icon sets per siteaccess
  composer.json
  src/IbexaPlatformAssetsBundle/bundle/DependencyInjection/Configuration/Parser/Assets.php
  src/IbexaPlatformAssetsBundle/bundle/DependencyInjection/IbexaPlatformAssetsExtension.php
  src/IbexaPlatformAssetsBundle/bundle/IbexaPlatformAssetsBundle.php
  src/IbexaPlatformAssetsBundle/bundle/Resources/config/services.yaml
  src/IbexaPlatformAssetsBundle/bundle/Resources/config/services/twig.yaml
  src/IbexaPlatformAssetsBundle/bundle/Twig/Extension/IconSetExtension.php
Labels: Improvement, Ready for review

#22 EZP-32098: Provided backwards compatibility for removed ez-icons.svg
  composer.json
  src/IbexaPlatformAssetsBundle/bundle/Resources/config/services.yaml
  src/IbexaPlatformAssetsBundle/bundle/Resources/config/services/events.yaml
  src/IbexaPlatformAssetsBundle/lib/Event/Subscriber/AssetsInstallCommandSubscriber.php
Labels: Improvement, Ready for review
